FROM ubuntu:focal-20220113

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update  && apt-get install -y sudo cmake gcc-7 g++-7 libboost1.71-all-dev libxerces-c-dev libcurl4-openssl-dev libsnmp-dev libmysqlclient-dev libjsoncpp-dev uuid-dev libusb-dev libusb-1.0-0-dev libftdi-dev swig liboctave-dev gpsd libgps-dev portaudio19-dev libsndfile1-dev libglib2.0-dev libglibmm-2.4-dev libpcre3-dev libsigc++-2.0-dev libxml++2.6-dev libxml2-dev liblzma-dev dpkg-dev libmysqlcppconn-dev libev-dev libuv1-dev git vim zip build-essential libssl-dev qtbase5-dev qtbase5-dev-tools curl libqhttpengine-dev libgtest-dev libcpprest-dev librdkafka-dev

RUN mkdir ~/V2X-Hub
COPY . /home/V2X-Hub

WORKDIR cd /usr/src/googletest/googletest
RUN mkdir ~/build
WORKDIR /usr/src/googletest/googletest/build
RUN cmake ..
RUN make
RUN cp libgtest* /usr/lib/
WORKDIR cd /usr/src/googletest/googletest
RUN rm -rf build
RUN mkdir /usr/local/lib/googletest
RUN ln -s /usr/lib/libgtest.a /usr/local/lib/googletest/libgtest.a
RUN ln -s /usr/lib/libgtest_main.a /usr/local/lib/googletest/libgtest_main.a
RUN ldconfig

WORKDIR /home/V2X-Hub/
RUN mkdir -p /home/V2X-Hub/ext
WORKDIR /home/V2X-Hub/ext/
RUN git clone https://github.com/usdot-fhwa-OPS/libwebsockets.git
WORKDIR /home/V2X-Hub/ext/libwebsockets/
RUN cmake -DLWS_WITH_SHARED=OFF .
RUN make
RUN make install

WORKDIR /home/V2X-Hub/ext
RUN git clone https://github.com/usdot-fhwa-OPS/qhttpengine.git
WORKDIR /home/V2X-Hub/ext/qhttpengine
RUN cmake .
RUN make 
RUN make install

WORKDIR /home/V2X-Hub/ext/ 
RUN git clone https://github.com/HowardHinnant/date.git
WORKDIR /home/V2X-Hub/ext/date
RUN cmake .
RUN make
RUN make install
RUN ldconfig 

WORKDIR /home/V2X-Hub/ext/server
RUN cmake -DCMAKE_BUILD_TYPE=Debug --config Debug .
RUN make
RUN make install

WORKDIR /home/V2X-Hub/ext/ccserver
RUN cmake -DCMAKE_BUILD_TYPE=Debug --config Debug . 
RUN make
RUN make install 
