version: '3.7'

services:
  db:
    image: usdotfhwaops/mysql:carma-streets
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=IVP
      - MYSQL_USER=IVP
      - MYSQL_PASSWORD=ivp
      - MYSQL_ROOT_PASSWORD=ivp
    network_mode: host
  php:
    image: usdotfhwaops/php:carma-streets
    container_name: php
    network_mode: host
    depends_on: 
      - db
    stdin_open: true
    tty: true

  v2xhub:
    image: usdotfhwaops/v2xhubamd:latest
    container_name: v2xhub
    network_mode: host
    restart: always
    depends_on: 
      - php
    volumes:
      - ./logs:/var/log/tmx
      - ./MAP:/var/www/plugins/MAP
